### ISSUE TITLE
Разобраться где именно происходит момент десериализации и сериализации данных в aspnet

### ISSUE THREAD

**Issue by pingvin1308** [emstd/CakeCrafter#11]
Где то в Middleware

**Comment by emstd** [comment]
Автоматическая сериализация и десереализация данных http-запроса попадает в middleware (в моем случае) при добавлении сервиса контроллеров, в паттерне MVC будет использоваться метод bulder.Services.AddMvc(), в моем случае builder.Services.AddController(). Этот метод возвращает объект MvcBuilder, на котором мы можем вызывать методы для настройки параметров сериализации и десереализации:
services.AddControllers().AddJsonOptions(options =>
    {
        //Настройка необходимых параметров
    });
