### ISSUE TITLE
Попробовать сделать generic контроллер для работы со справочной информацией

### ISSUE THREAD

**Issue by pingvin1308** [emstd/CakeCrafter#2]
Таким образом можно попробовать объединить контроллеры вкусов, категорий и ингредиентов

**Comment by emstd** [comment]
Сделал generic контроллер, обновил на данный момент с его помощью CategoryController, хотелось бы какой-нибудь фидбек, чтобы решить обновлять ли остальные контроллеры или так не пойдет :)

**Comment by pingvin1308** [comment]
В generic контроллере нужно будет сделать общую логику, которую будешь переиспользовать для контроллеров где нужен тупо базовый круд, без особой логики
