### ISSUE TITLE
почему nvarchar(max) это плохо или хорошо?

### ISSUE THREAD

**Issue by pingvin1308** [emstd/CakeCrafter#24]
в комментарии нужно написать ответ на вопрос + агрументы

**Comment by emstd** [comment]
Нашел два интересных ответа. Вкратце, использовать nvarchar(max) нужно только тогда, когда это действительно необходимо. Зачем хранить адрес/имя/email, которые явно не будут более ~80 символов, в столбце, каждая строка которого будет занимать максимально возможный объем памяти для типа nvarchar и varchar.
1) Чтобы что-то отсортировать, это что-то нужно сначала поместить в память. Как понять сколько памяти нужно? Вообще, нам известно сколько какой тип данных занимает места. А что же со строками переменной длины? А вот с ними интереснее. При выделении памяти для сортировок/hash join, SQL Server считает, что в среднем они заполнены наполовину. И выделяет под них память как (размер / 2) * ожидаемое количество строк. Но varchar(max) может хранить аж 2Гб – сколько же выделять? SQL Server считает, что там будет половина от varchar(8000) – т.е. примерно 4 кб на строку.
2) when you store data to a VARCHAR(N) column, the values are physically stored in the same way. But when you store it to a VARCHAR(MAX) column, behind the screen the data is handled as a TEXT value. So there is some additional processing needed when dealing with a VARCHAR(MAX) value. (only if the size exceeds 8000)
VARCHAR(MAX) or NVARCHAR(MAX) is considered as a 'large value type'. Large value types are usually stored 'out of  row'. It means that the data row will have a pointer to another location where the 'large value' is stored. By default sql server will try to accomodate the value 'in row' but if it could not, it will store the large values 'out of row'. When values are stored 'out of row' there will be slight processing overhead in reading the information.
