### ISSUE TITLE
Найти ответ на вопрос "Чем REST отличается от RPC?"

### ISSUE THREAD

**Issue by pingvin1308** [emstd/CakeCrafter#3]

**Comment by emstd** [comment]
Постараюсь здесь дать краткий ответ для себя своими словами.
Это парадигмы разработки web API.
REST - как правило работает поверх HTTP, в создании HTTP один из главных разработчиков так же является основателем архитектуры REST. Архитектура сосредотачивается на ресурсах и объектах, использует в работе все HTTP-глаголы (CRUD). Не хранит состояние клиента, то есть каждый запрос не знает, что было в других запросах. Для обращения с клиента на сервер не нужно знать названия функций и их аргументы, используемые на сервере, нужно знать URL, в соответствии с которым происходит роутинг.

RPC - вызов удаленных процедур, при котором клиент вызывает методы на сервере таким же образом, как если бы они были доступны локально, то есть с помощью глагола POST происходит вызов метода, в который передаются параметры, затем вся логика этого метода выполняется на стороне сервера и отправляется ответ. Для использования соответственно нужно знать названия методов, которые хотим вызывать и список аргументов. Архитектура сосредотачивается не на ресурсах и объектах, а на методах и действиях. Может работать не только поверх HTTP - UDP, gRPC и так далее.
