### ISSUE TITLE
Почитать статью про конфигурации приложения на aspnet

### ISSUE THREAD

**Issue by pingvin1308** [emstd/CakeCrafter#9]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0

найти ответ на вопрос 
"Какое значение будет взято если в приложении в appsettings.json, args[] и env variables указано один и тотже ключ с разными значениям?" 
"Чем контролируется этот порядок?"

**Comment by emstd** [comment]
Пока успел изучить следующее: есть такая штука в Bulder.Configuration как ConfigurationProviders. Здесь хранится перечень различных провайдеров: 
{EnvironmentVaribales} Prefix: ASP.NET core, 
{MemoryConfigurationProvider}, 
{EnvironmentVaribales} Prefix: DOTNET, 
{jsonConfigurationProvider} 'appsettings.json',
{jsonConfigurationProvider} 'appsettings.Development.json',
{EnvironmentVaribales} Prefix: '',
{ChainedConfigurationProvider}

например, конфигурацию ConnectionStrings в Builder.Configuration, объявленный в файле json, мы получим тот, который указан последним в списке провайдеров, то есть 'appsettings.Development.json'.
Appsettings как правило не коммитится в целях безопасности, так как чаще хранит всякие строки подключения, которые опасно хранить на сервере. 
Следующий способ secrets.json. Можем так же задавать, удалять, редактировать настройки, при добавлении этого провайдера он встанет ниже предыдущих в списке, поэтому теперь например ConnectionStrings будут браться в билдер из этого файла.
Далее по приоритету идут переменные среды окружения (EnvironmentVariables), задавать их можно много где, например через launchSettings.json, в общем везде, где мы их пропишем, они будут вычитываться.
Далее еще выше по приоритету идут аргументы командной строки [args], для них так же создается провайдер в списке, то есть аргументы командной строки перекрывают настройки всех предыдущих параметров.
